language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then mvn clean source:jar javadoc:javadoc deploy --settings travis_settings.xml; fi'
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then mvn clean verify; fi'

# travis encrypt -r bootique/bootique-kotlin "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-kotlin "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: ""
    - secure: ""

